import Header from "@/Component/Shared/Header";
import "./globals.css";
import { ApolloWrapper } from "../Component/lib/apolloWrapper.jsx";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
