import Header from "@/Component/Shared/Header";
import "./globals.css";
import { ApolloWrapper } from "../Component/lib/apolloWrapper.jsx";
import Container from "@/Component/UI/Container";

export const metadata = {
  title: "rickandmorty",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Container>
          <Header />
          <ApolloWrapper>{children}</ApolloWrapper>
        </Container>
      </body>
    </html>
  );
}
